# Generated by Django 2.0.7 on 2024-09-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20240912_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
